//copy Blocks.dll into Assets/Plugins directory
//Procedural textures are generated by NVIDIA CUDA PTX assembly code (kernel "mainImage" from Blocks.cu),
//then passed to Unity Engine.
using System;
using UnityEngine;
using System.Runtime.InteropServices;

public class Blocks : MonoBehaviour 
{
	[DllImport("Blocks", EntryPoint = "Render")]
	static extern IntPtr Render (float time);
	[DllImport("Blocks", EntryPoint = "Clear")]
	static extern void Clear ();

	private byte[] buffer;
	private Texture2D image;
	private IntPtr handle;

	void Start()
	{
		buffer = new byte[1024*1024*4];
		image = new Texture2D(1024, 1024, TextureFormat.RGBA32, false);
		GetComponent<Renderer>().material.mainTexture = image;
	}
	
	void Update()
	{
		handle = Render(Time.time);
		Marshal.Copy(handle, buffer, 0, 1024*1024*4);
		image.LoadRawTextureData(buffer);
		image.Apply();
		Clear();
	}
}